 #include <ncurses.h>

void animatedTitle(int frame){

	if (frame == 1)	printw("                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n             .,,,,,                                                             ");
	if (frame == 2) printw("                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n         w,ggggggg&                                                             \n         $$$$$$$$$$                                                             \n         ¨|l$$$$|||                                                             ");
	if (frame == 3) printw("                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n         $$$$$$$$$$                                                             \n         $$$$$$$$$$                                                             \n          '\"$$$$|'¨                                                             \n            $$$$|                                                               \n            $$$$|                                                               ");
	if (frame == 4) printw("                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n                                                                                \n         ,,,;;;;;;g                                                             \n         $$$$$$$$$$                                                             \n         \"**$$$$***                                                             \n            $$$$|                                                               \n            $$$$|                                                               \n            $$l$|                                                               \n            $@$@|   ,,,,,,,,,                                                   \n            $$$$|  |$$$$$$ll&k                                                  ");
	if (frame == 5) printw("                                 l|ll|                                          \n                                 l&l&|                                          \n                                                                                \n                                                                                \n                                                                                \n         ggggggggg$$                                                             \n         $$$$$$$$$$$                                                             \n            $$$$|                                                               \n            $$$$|                                                               \n            $$$$|                                                               \n            $$@@|                                                               \n            $$$@|  |$$$&$$$$§k                                                  \n            $$$$|  |llllllll@k                                                  \n                   jlll@                                                     \n                   ]llll@@$||                                                   ");
	if (frame == 6) printw("                              \"|\"$lll|||                                        \n                                 &&&$|                                          \n                                 llll|                                          \n                                 llll|                                          \n         ggggggggg$              llll|                                          \n         $$$$$$$$$$              l||l|                                          \n          'l$$$$|\"¨              °***|                                          \n            $$$$|                                                               \n            $$$$|  |$$$$$$$$&k                                                  \n            $$@@|  |$lllllll§k                                                  \n            $$$@|  ]lll@||||\"                                                   \n            $$$$|  ]lllll@@&|                                                   \n            ''\"\"¨  ]$$$$$&||                                                    \n                   ]l$l@|¨                                                      \n                   ]llll$$$$$$,                                                 ");
	if (frame == 7) printw("                                                                                \n                                                                                \n                                                                                \n                               @@@@$$$$$$                                        \n         ggggggggg$            l||ll||lll                                       \n         $$$$$$$$$$ $@$&@@@@@r    lll|                                          \n            $$$$|   $ll&ll&$&k    lll|                                          \n            $$$$|   lll$|         lll|                                          \n            $$$$|   lll||l$&|     lll|                                          \n            $$@@|   &$$$$$$|$     lll|                                          \n            $$$@|   $ll@|         ||l|                                          \n            $$$$|   lll$@@@@@@,   ''''                                          \n            ''\"\"¨   1lllllllll$          ,,,,,,,                                \n                                         $$$$$$$$@g                             \n                                         $$$$@g$$$$|                            ");
	if (frame == 8) printw("                                                                                \n                                                                                \n                                                                                \n                                                                                \n         ggggggggg$ §@@@@$$$$  l@lllll$$$                                        \n         $$$$$$$$$$ $lllllll§  l||ll||lll                                        \n            $$$$|   lll@          ll||'                                        \n            $$$$|   lll|l@@&      lll|                                          \n            $$$$|   $$l$$$||      lll|                                          \n            $$@@|   lll@|         lll|                                          \n            $$$@|   llll$$$$$$,   lll|   §@@@@@@@@,                             \n            $$$$|   *lllllllll    ||l|   $$$$$$$$$$|                            \n                                         $§$    $$@|                            \n                                         $$$   @@$|                             \n                                         $$$$|$$$$g                             ");
	if (frame == 9) printw("                                                     lllk   lll{                \n                                                     'l|llll|ll                 \n                                                       llllll°                  \n                                                                                \n         ggggggggg$ §@@@@$$$$k l@lllll$$$                                       \n         $$$$$$$$$$ $lllllll§k l||ll||lll                                       \n            $$$$|   lll@          lll|                                          \n            $$$$|   lll|l@@&      lll|   $@@@@@@@g,                             \n            $$$$|   $$l$$$||      lll|   $$$$$$$$$$|                            \n            $$@@|   lll@          lll|   &&&$    $$|                            \n            $$$@|   llll$$$$$$,   lll|   $$@$   g@|                             \n            $$$$|   lllllllllll   ||l|   $$$$|$$$$g                             \n                                         @$$$|$$$$$g                            \n                                         @$$$|  $$$@                            \n                                         @$$$|   jl@                            ");
	if (frame == 10) printw("                                                     ll|°   lll{                \n                                                    }l|l    |ll|                \n                                                     lll    }lll                \n                                                     lll,   $|l{                \n         ggggggggg$ §@@@@$$$$k l@lllll$$ &gggg@@gg   }lll&g$||l                 \n         $$$$$$$$$$ llllllll§k l||ll||ll $$$$$$$$$$   'llllll&                  \n            $$$$|   lll@          lll|   &$$$   $$$|                            \n            $$$$|   lll|l@@&&     lll|   $@@$  @@#|                            \n            $$$$|   $$l$$$|||     lll|   $$$$]@$$$µ                             \n            $$@@|   lll@|'        lll|   @$$$|\"$$$$µ                            \n            $$$@|   llll$$$$$$    lll|   @$$$| '$$$@                            \n            $$$$|   *lllllllll    ||l|   @$$$|   $l@                            \n                         \n\n                                                                                \n\n                                                                                ");
	if (frame == 11) printw("                                                                                \n                                                      ,;$ll$&,                  \n                                                     ,ll|l|l|l&                 \n                                                     lll'  'lllk                \n         ggggggggg$ §@@@@$$$$kl l@lllll$ $$@@@@@@g,  lll    }|l|                \n         $$$$$$$$$$ $lllllll§k| ||ll||ll $$$$$$$$$$| ll|    }lll              |$\n            $$$$|   lll            ll|   &&&$   $$$| lll    l|l{              |l\n            $$$$|   lll|l@@&&      ll|   $$$$  @g@|¨ ll|lwwéll|               |\"\n            $$$$|   $$l$$$|||      ll|   $$$$|$$$$g   lll|llll¨               | \n            $$@@|   lll            ll|   @$$$|\"$$$$g    '\"\"'                  | \n            $$$@|   llll$$$$$$,    ll|   @$$$|  $$$@                          |g\n            $$$$|   llllllllljy    |l|   @§$$|   j$@                          |@\n\n                                                                                \n                                                                                ");
	if (frame == 12) printw("                                                                                \n                                                                                \n                                                                                \n                                                                                \n         ggggggggg$ §@@@@$$$$kl @lllll$$ $@@@@@@@g,    ,g&&gw            ,;ggggg\n         $$$$$$$$$$ $lllllll§k| ||ll||ll $$$$$$$$$$  ,$||l|llly        '$$$$$$$$\n            $$$$|   lll           lll|   &&&$   $$$  $ll&  \"lllr        llll$\"\"|\n            $$$$|   lll|l@@&      lll|   $$$$  @g@|  lll    }|l|       '\"$ll|k  \n            $$$$|   $$l$$$||      lll|   $$$$|$$$$g  lll    }lll       '  j|||jµ\n            $$@@|   lll           lll|   @$$$|\"$$$$g ||l    |ll|       '   \"@|||\n            $$$@|   llll$$$$$$,   lll|   @$$$|  $$$@ ll|&,,;ll|°       'gggm@$@|\n            $$$$|   lllllllll|y   ||l|   @§$$|   j$@  l||lllll\"        |@lllllll\n\n                                                                                \n                                                                                ");
	if (frame == 13) printw("                                                                                \n                                                                                \n                                                                                \n                                                                                \n         ggggggggg$ §@@@@$$$$kl @lllll$$ $@@@@@@@g,    ,g&&gw      ,ggggggw     \n         $$$$$$$$$$ $lllllll§k| ||ll||ll $$$$$$$$$$|  $||l|llly   #$$$$$j&|,    \n            $$$$|   lll           lll|   &&&$   $$$| $ll&  \"lllr l$llj\"    \"    \n            $$$$|   lll|l@@&      lll|   $$$$  @g@|  lll    }|l| ¨lll|&µ        \n            $$$$|   $$l$$$||      lll|   $$$$|$$$$g  lll    }lll   \"y|||@       \n            $$@@|   lll           lll|   @$$$|\"$$$$g ||l    |ll|   .11|||1r     \n            $$$@|   llll$$$$$$,   lll|   @$$$|  $$$@  l|&,,;ll|| .gggm$&@|$|    \n            $$$$|   llllllllljy   ||l|   @§$$|   j$@  \"||lllll\" l$llllllll     \n                                                                                \n                                                                                ");

	return;
}

/* Animation de démarrage */
void startAnimation(){
	for (int i = 1; i < 13; ++i)
	{
		int key;
		erase();
		animatedTitle(i);
		refresh();
		timeout(100);
		key = getch();
		if (key != ERR) i = 13;
	}

	return;
}

/* Animation de Sortie */
void exitAnimation(){
	for (int i = 12; i >= 0; --i)
	{	
		int key;
		erase();
		animatedTitle(i);
		refresh();
		timeout(100);
		key = getch();
		if (key != ERR) i = -1;
	}

	return;
}